# Generated by Django 2.1.7 on 2019-03-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField(max_length=2083, verbose_name='原始url')),
                ('short_key', models.CharField(max_length=10, null=True, unique=True, verbose_name='短链接key')),
                ('is_custom', models.BooleanField(default=False, verbose_name='是否自定义')),
            ],
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0, verbose_name='访问计数')),
                ('short_url', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='view_count', to='short_url.ShortUrl')),
            ],
        ),
    ]
